language: generic
env:
  global:
    - SSH_KEY="travis_key"
    - GIT_NAME="Josh Chase"
    - GIT_EMAIL="josh@jec.pw"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="hugo"
script:
  - ./bin/hugo version
  - ./bin/hugo
after_success:
  - echo "www.joshandmarina.wedding" > ./public/CNAME
  - ./bin/deploy.sh
before_install:
  - openssl aes-256-cbc -K $encrypted_9a039e3ca961_key -iv $encrypted_9a039e3ca961_iv -in travis_key.enc -out travis_key -d

